create table legalforms (
                            id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            legal_form VARCHAR(30) UNIQUE
);
insert into legalforms (legal_form) values ('ООО');
insert into legalforms (legal_form) values ('ИП');
insert into legalforms (legal_form) values ('АО');
insert into legalforms (legal_form) values ('ОДО');

create table clients (
                         client_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(50) NOT NULL UNIQUE,
                         short_name VARCHAR(50) NOT NULL,
                         address VARCHAR(50) NOT NULL,
                         legal_form_id int references legalforms(id) ON DELETE CASCADE
);
insert into clients (name, short_name, address, legal_form_id) values ('Wikivu', 'Babbleset', '12900 Lakewood Gardens Plaza', 1);
insert into clients (name, short_name, address, legal_form_id) values ('Feedspan', 'Lajo', '193 Goodland Trail', 2);
insert into clients (name, short_name, address, legal_form_id) values ('Dynabox', 'Twitterbridge', '43848 Laurel Hill', 2);
insert into clients (name, short_name, address, legal_form_id) values ('Voomm', 'Eadel', '09491 Old Gate Point', 3);
insert into clients (name, short_name, address, legal_form_id) values ('Bubblebox', 'Plambee', '4 Delaware Circle', 3);
insert into clients (name, short_name, address, legal_form_id) values ('Meetz', 'Babbleopia', '09 Melrose Street', 4);

create table banks (
                       bank_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       bank_name VARCHAR(9) NOT NULL UNIQUE,
                       bank_code VARCHAR(50) NOT NULL UNIQUE
);
insert into banks (bank_name, bank_code) values ('sber', '072502168');
insert into banks (bank_name, bank_code) values ('VTB', '494953635');
insert into banks (bank_name, bank_code) values ('Alfa-bank', '593281546');
insert into banks (bank_name, bank_code) values ('PSB', '120387454');
insert into banks (bank_name, bank_code) values ('Tinkoff', '118644704');

create table deposit (
                         deposit_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         client_id int REFERENCES clients(client_id) ON DELETE CASCADE ,
                         bank_id int REFERENCES banks(bank_id) ON DELETE CASCADE,
                         opening_date DATE DEFAULT current_date,
                         interest DECIMAL(4,2) NOT NULL,
                         duration_in_months INT NOT NULL
);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (1, 5, '30/08/2016', 1.49, 40);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (2, 1, '06/06/2017', 16.63, 87);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (3, 4, '20/05/2015', 21.59, 62);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (4, 5, '18/03/2020', 23.12, 35);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (4, 2, '21/10/2017', 4.16, 16);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (3, 3, '03/07/2014', 4.87, 69);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (2, 5, '07/12/2012', 2.04, 4);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (1, 2, '30/10/2019', 29.36, 89);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (2, 4, '10/05/2011', 11.7, 35);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (1, 3, '24/06/2017', 19.03, 35);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (3, 5, '11/02/2014', 6.03, 53);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (4, 2, '27/05/2016', 5.87, 44);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (5, 5, '19/03/2019', 3.38, 66);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (5, 2, '13/12/2011', 19.34, 95);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (1, 3, '15/08/2015', 11.06, 16);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (2, 5, '20/10/2012', 20.93, 98);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (3, 5, '19/09/2015', 16.44, 64);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (5, 5, '29/08/2018', 4.49, 39);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (4, 2, '22/12/2016', 23.15, 44);
insert into deposit (client_id, bank_id, opening_date, interest, duration_in_months) values (3, 2, '16/03/2017', 24.27, 22);